import dotenv from "dotenv";
dotenv.config();

const JWT_USER_PASSWORD=process.env.JWT_USER_PASSWORD;
const JWT_ADMIN_PASSWORD=process.env.JWT_ADMIN_PASSWORD;
const STRIPE_SECRET_KEY= "sk_test_51RLHZW59lEuEB98gYGerRpA4HHMkVH66QLeQ1nt87zZI3tBHMrzo1FfAkpdNp4EQGQlM4eQVV4SXPlIV2BM2oRVq00DG4woUKe";

export default {
    JWT_USER_PASSWORD,
    JWT_ADMIN_PASSWORD,
     STRIPE_SECRET_KEY
}